### ISSUE TITLE
`remove_host_restrictions` functionality no longer in the public interface

### ISSUE THREAD

**Issue by chadwhawkins** [miketheman/pytest-socket#106]
Hi there!

First of all, thank you for your work writing and maintaining this package. My team is using the package to limit connections to the outside world by default for all unit tests but then enable outside access for a handful of integration tests. We use a yield fixture with version `0.4.1` to do this:

```
@pytest.fixture
def enable_network_requests():
    remove_host_restrictions()
    yield
    socket_allow_hosts(["127.0.0.1", MOTO_RESOURCE_ADDRESS])
```

I tried updating to `0.5.0` but see that `remove_host_restrictions` is no longer in the public interface. Is there a possibility to bring it back or perhaps some other method I'm missing? Thanks!

**Comment by miketheman** [comment]
Hi @chadwhawkins !
Thanks for the kind words.

With 0.5.0 a bit of restructuring went on, and the original approach of an `autouse` fixture was replaced by a test-specific setup and [teardown](https://github.com/miketheman/pytest-socket/blob/2e3ac6506605e31ec2005213dc395f98c52866bf/pytest_socket.py#L152-L153) step that should restore the original behaviors post-test.

I'm curious what led to the creation of your custom fixture - is it possible that was a workaround due to the autouse fixture misbehaving and its removal should change the need for the custom fixture?

It _should_ be the case that if you pass the plugin's [`socket_enabled ` fixture to a test](https://github.com/miketheman/pytest-socket#:~:text=To%20enable%20specific%20tests%20use%20of%20socket%2C%20pass%20in%20the%20fixture%20to%20the%20test%20or%20use%20a%20marker%3A), that should enable the network requests as you wish?

**Comment by chadwhawkins** [comment]
@miketheman thanks for the reply!

I'm not sure what lead to the creation of the custom fixture as that predates my involvement in the code. Before creating this issue I tried to get `socket_enabled` to work with no luck. My test setup function looked like this:

```
def pytest_runtest_setup():
    socket_allow_hosts(allowed=["127.0.0.1", MOTO_RESOURCE_ADDRESS])
```

However, with a bit more investigation it looks like I need to explicitly disable everything before allowing select hosts, e.g.:

```
def pytest_runtest_setup():
    disable_socket()
    socket_allow_hosts(allowed=["127.0.0.1", MOTO_RESOURCE_ADDRESS])
```

I was assuming that allowing only specific hosts implied that all others would be disabled. Just wanted to confirm that's the intended pattern. Thanks!

**Comment by miketheman** [comment]
@chadwhawkins glad it's working out! 
I usually prefer the command-line options `pytest ... --disable-socket --socket-allow-hosts="127.0.0.1,..."` as a way to not have to use a custom `pytest_runtest_setup()`, but see that you're using a constant for the moto address, so this approach ought to work in a similar fashion.

Closing this one out!
