### ISSUE TITLE
socket_enabled does not work with pytest.mark.parametrize

### ISSUE THREAD

**Issue by fj-dt** [miketheman/pytest-socket#56]
When I do:

```python
@pytest.mark.parametrize(
    "url",
    [
        "https://google.com",
        "https://amazon.com",
        "https://microsoft.com",
    ],
)
def test_domain(url, socket_enabled):
    requests.get(url)
```

The first URL is blocked and the others are allowed.
The error happens with `@pytest.mark.enable_socket` as well.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/63464773/112062852-cef1b380-8b60-11eb-9d8f-8a8d8468eeaf.png">

My setup.cfg:

```
[tool:pytest]
addopts = --allow-hosts=127.0.0.1
```

**Comment by miketheman** [comment]
Thanks for the detailed report!

This seems like a logical bug, and I'll have to dig into it a bit more - since from the outset, I think it's confusing to the user that passing `--allow-hosts=...` without the `--disable-socket` isn't exactly the intended behavior either.

I can confirm that setting the `.ini` to:

```ini
[pytest]
addopts = --disable-socket --allow-hosts=127.0.0.1
```

and running the test, all 3 requests are blocked, since none of the target IPs match `127.0.0.1`.

Can you help me understand what outcome you expected?

**Comment by fj-dt** [comment]
Hello Mike.

I tried your configuration but it does the opposite of what I expect.

I expect that, by default it does not allow socket. So when I pass `socket_enabled` in my test, then they should be allowed.
In my example, the first one is not allowed, then the two others are. The three of them should be allowed since I used `socket_enabled`.

By adding `--disable-socket` things get worse, as none of them are allowed, although I have the `socket_enabled` as argument in my test. So I think you just found another issue.

**Comment by miketheman** [comment]
@fj-dt I wrote a test here: https://github.com/miketheman/pytest-socket/commit/3b61b28d0f818b80de0ce93f87ac99fdfce7eac8

If I read your desire correctly, you're expecting the inline `socket_enabled` to override the config setting, and allow those three remote calls, instead of failing all three?

**Comment by fj-dt** [comment]
@miketheman Correct. 👍
